{
  "build_revision"     => "8ee7f809504232ae7d6ec765824098f36b9e2d51",
  "pages_env"          => "dotcom",
  "versions"           => {
      "jekyll"         => "1.4.3",
      "karmdown"       => "1.3.1",
      "liquid"         => "2.5.5",
      "maruku"         => "0.7.0",
      "rdiscount"      => "2.1.7",
      "redcarpet"      => "2.3.0",
      "RedCloth"       => "4.2.9",
      "github-pages"   => "16",
      "ruby"           => "2.1.0"
    },
  "project_title"      => "Example",
  "project_tagline"    => "Some example site.github output",
  "owner_name"         => "github",
  "owner_url"          => "https://github.com/github",
  "owner_gravatar_url" => "https://github.com/github.png",
  "repository_url"     => "https://github.com/github/example",
  "repository_nwo"     => "github/example",
  "repository_name"    => "example",
  "zip_url"            => "https://github.com/github/example/zipball/gh-pages",
  "tar_url"            => "https://github.com/github/example/tarball/gh-pages",
  "clone_url"          => "https://github.com/github/example.git",
  "releases_url"       => "https://github.com/github/example/releases",
  "issues_url"         => "https://github.com/github/issues",
  "wiki_url"           => nil, # when wiki is disabled, otherwise the URL
  "language"           => "PHP",
  "is_user_page"       => false,
  "is_project_page"    => true,
  "show_downloads"     => true,
  "url"                => "http://username.github.io/example" # (or the CNAME)
}
